import {
  PACK_CACHE_NAME,
  TOPO_CACHE_NAME,
  cacheNameForUrl,
  toManifestInput,
  toPlanIndexEntry,
  type PackPlan,
  type PackPlanIndexEntry,
} from './packBuilder';
import {
  assetsStillPinnedElsewhere,
  computePackReadiness,
  deleteManifest,
  getManifest,
  listManifests,
  markSectionReady,
  putManifest,
} from './downloadManifests';
import type { DownloadManifestRecord } from './db';

/**
 * Cache-Storage pinning for user-managed packs (ADR 0012 decisions 3–5).
 *
 * This is the SW-layer half of the manifests lane: `pin` fetches every asset
 * URL of a plan (bounded concurrency, one retry), stores it with `cache.put`,
 * and flips a section's readiness only AFTER that section's URLs are stored —
 * so a crashed or failing pin leaves an honestly partial manifest, never a
 * silently "ready" one. `verify` re-checks every URL against the caches
 * (browser storage CAN be evicted) and downgrades sections that lost data.
 * `remove` deletes only the URLs no other manifest still pins, and never
 * touches anything but the pack caches + the manifest store — logs, favorites,
 * trips, and photos are structurally unreachable from here.
 *
 * Cache layout (see packBuilder.ts):
 *  - everything → `trout-packs-v1`;
 *  - terrain tiles → the existing `topo-cache`, because the service worker's
 *    CacheFirst runtime route already serves that cache offline.
 *
 * Service-worker fallback note: this project's SW is generated by
 * vite-plugin-pwa generateSW (vite.shared.ts `workbox:` block), which cannot
 * carry a custom fetch handler, so a pinned JSON miss during a plain offline
 * `fetch` is recovered by the APP layer instead — fetchSnapshot's
 * caches.match recovery tier searches ALL caches (lib/snapshots.ts), which
 * finds `trout-packs-v1`. Terrain tiles need no fallback (CacheFirst route).
 * Wiring a dedicated SW fetch fallback requires switching that one project to
 * injectManifest — recorded as the remaining step in the lane report.
 */

/** Per-section URL attribution, persisted beside the caches so Verify and
 *  Remove survive a browser restart (the Dexie record intentionally carries
 *  readiness only). Best-effort: a lost index means "attribution unknown",
 *  never a guessed section state. */
const PLAN_INDEX_KEY = 'trout:pack-plans:v1';

function readPlanIndex(): Record<string, PackPlanIndexEntry> {
  try {
    const raw = localStorage.getItem(PLAN_INDEX_KEY);
    return raw ? (JSON.parse(raw) as Record<string, PackPlanIndexEntry>) : {};
  } catch {
    return {};
  }
}

function writePlanIndexEntry(entry: PackPlanIndexEntry): void {
  try {
    const index = readPlanIndex();
    index[entry.id] = entry;
    localStorage.setItem(PLAN_INDEX_KEY, JSON.stringify(index));
  } catch {
    /* private mode / storage pressure: pin still works, Verify loses
       per-section attribution and reports that honestly */
  }
}

function dropPlanIndexEntry(id: string): void {
  try {
    const index = readPlanIndex();
    if (delete index[id]) localStorage.setItem(PLAN_INDEX_KEY, JSON.stringify(index));
  } catch {
    /* nothing durable to update */
  }
}

// ── Cache Storage plumbing ──────────────────────────────────────────────────

async function openCache(name: string): Promise<Cache> {
  if (typeof caches === 'undefined') throw new Error('Cache Storage unavailable in this browser');
  return caches.open(name);
}

async function urlPresent(url: string): Promise<boolean> {
  try {
    const cache = await openCache(cacheNameForUrl(url));
    const hit = await cache.match(url);
    return hit !== undefined && hit.ok;
  } catch {
    return false;
  }
}

/** Run async work over a bounded pool so a pack with many tiles never
 *  stampedes the network (same discipline as useFishabilityIndex). */
async function mapPool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<PromiseSettledResult<R>[]> {
  const results: PromiseSettledResult<R>[] = new Array(items.length);
  let cursor = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor++;
      try {
        results[index] = { status: 'fulfilled', value: await fn(items[index]!) };
      } catch (error) {
        results[index] = { status: 'rejected', reason: error };
      }
    }
  });
  await Promise.all(workers);
  return results;
}

const PIN_CONCURRENCY = 4;

/** One network attempt, then a single retry — a flaky radio must not fail a
 *  section that a second try would finish (mirrors the app's retry: 1). */
async function fetchForPin(url: string): Promise<Response> {
  try {
    return await assertOk(await fetch(url, { headers: { accept: '*/*' } }), url);
  } catch (first) {
    return assertOk(await fetch(url, { headers: { accept: '*/*' } }), url, first);
  }
}

function assertOk(res: Response, url: string, previous?: unknown): Response {
  if (!res.ok) {
    const error = new Error(`HTTP ${res.status} for ${url}`);
    (error as Error & { cause?: unknown }).cause = previous ?? new Error(`HTTP ${res.status} for ${url}`);
    throw error;
  }
  return res;
}

function isQuotaError(error: unknown): boolean {
  const name = (error as { name?: unknown } | null)?.name;
  if (name === 'QuotaExceededError' || name === 'NS_ERROR_DOM_QUOTA_REACHED') return true;
  const message = (error as { message?: unknown } | null)?.message ?? '';
  return /quota/i.test(String(message));
}

/** Trivially-available storage estimate for honest quota copy (never invented). */
export async function storageEstimate(): Promise<{ usage: number; quota: number } | null> {
  try {
    const estimate = await navigator.storage?.estimate?.();
    if (!estimate || typeof estimate.usage !== 'number' || typeof estimate.quota !== 'number') return null;
    return { usage: estimate.usage, quota: estimate.quota };
  } catch {
    return null;
  }
}

// ── Pin ─────────────────────────────────────────────────────────────────────

export interface PinProgress {
  manifestId: string;
  sectionKey: string;
  label: string;
  done: number;
  total: number;
}

export interface PinResult {
  manifest: DownloadManifestRecord | undefined;
  /** True when every REQUIRED section verified present. */
  ok: boolean;
  /** Pinning was refused up front (honest, nothing half-fetched). */
  offline?: boolean;
  /** Storage ran out mid-pin; remaining sections were left not-ready. */
  quota?: boolean;
  /** URLs that could not be pinned after the retry (per failing section). */
  failures: Array<{ sectionKey: string; url: string; error: string }>;
}

/**
 * Pin a plan: persist the manifest first (all sections not-ready — a crash
 * must never leave an optimistic record), then fetch + store per section,
 * flipping readiness only after that section's URLs are actually in the cache.
 */
export async function pin(
  plan: PackPlan,
  onProgress?: (progress: PinProgress) => void,
): Promise<PinResult> {
  // Re-pinning replaces the record wholesale: sections reset to not-ready so
  // the manifest never describes more than the caches provably hold.
  await putManifest(toManifestInput(plan));
  writePlanIndexEntry(toPlanIndexEntry(plan));

  const failures: PinResult['failures'] = [];
  let quota = false;

  if (typeof navigator !== 'undefined' && navigator.onLine === false) {
    return {
      manifest: await getManifest(plan.id),
      ok: false,
      offline: true,
      failures,
    };
  }

  try {
    const cachesByUrl = new Map<string, Cache>();
    for (const url of plan.assetUrls) {
      const name = cacheNameForUrl(url);
      if (!cachesByUrl.has(name)) cachesByUrl.set(name, await openCache(name));
    }

    for (const section of plan.sections) {
      let done = 0;
      const total = section.urls.length;
      const report = () =>
        onProgress?.({ manifestId: plan.id, sectionKey: section.key, label: section.label, done, total });

      report();
      let sectionBytes = 0;
      let allBytesKnown = total > 0;
      const results = await mapPool(section.urls, PIN_CONCURRENCY, async (url) => {
        const res = await fetchForPin(url);
        const lengthHeader = res.headers.get('content-length');
        if (lengthHeader === null || Number.isNaN(Number(lengthHeader))) allBytesKnown = false;
        else sectionBytes += Number(lengthHeader);
        await cachesByUrl.get(cacheNameForUrl(url))!.put(url, res);
        done += 1;
        report();
      });

      const failed = results
        .map((r, i) => ({ r, url: section.urls[i]! }))
        .filter((x) => x.r.status === 'rejected') as Array<{
        url: string;
        r: PromiseRejectedResult;
      }>;
      for (const f of failed) {
        failures.push({
          sectionKey: section.key,
          url: f.url,
          error: f.r.reason instanceof Error ? f.r.reason.message : String(f.r.reason),
        });
        if (isQuotaError(f.r.reason)) quota = true;
      }

      // Readiness follows storage, not intent: only a fully-stored section
      // flips ready. A quota failure aborts the remaining sections — they
      // stay not-ready and the caller gets the honest quota flag.
      await markSectionReady(plan.id, section.key, failed.length === 0, allBytesKnown ? sectionBytes : undefined);
      if (quota) break;
    }
  } catch (error) {
    // Cache Storage unavailable or a hard failure between sections: the
    // manifest keeps whatever per-section truth was already recorded.
    if (isQuotaError(error)) quota = true;
    else failures.push({ sectionKey: '*', url: '', error: error instanceof Error ? error.message : String(error) });
  }

  const manifest = await getManifest(plan.id);
  return {
    manifest,
    ok: manifest ? computePackReadiness(manifest.sections).requiredReady : false,
    quota,
    failures,
  };
}

// ── Verify ──────────────────────────────────────────────────────────────────

export interface VerifyResult {
  manifest: DownloadManifestRecord | undefined;
  readiness: ReturnType<typeof computePackReadiness>;
  /** True when the plan index was lost and per-section truth can't be checked. */
  attributionLost?: boolean;
}

/**
 * "Verify offline readiness": match every pinned URL against its cache and
 * record per-section truth. Evicted sections downgrade; nothing is ever
 * re-marked ready on faith. Requires no network.
 */
export async function verify(manifest: DownloadManifestRecord): Promise<VerifyResult> {
  const index = readPlanIndex();
  const entry = index[manifest.id];
  const readyByKey = new Map<string, boolean>();

  if (!entry) {
    // No attribution (e.g. localStorage cleared while caches survived):
    // refuse to guess — every section reads not-ready until a re-pin.
    for (const section of manifest.sections) readyByKey.set(section.key, false);
    for (const section of manifest.sections) await markSectionReady(manifest.id, section.key, false);
    const next = await getManifest(manifest.id);
    return {
      manifest: next,
      readiness: next ? computePackReadiness(next.sections) : computePackReadiness([]),
      attributionLost: true,
    };
  }

  for (const section of entry.sections) {
    const results = await Promise.all(section.urls.map((url) => urlPresent(url)));
    readyByKey.set(section.key, results.every(Boolean));
  }
  // Sections the index doesn't know (schema drift) are honestly unverified.
  for (const section of manifest.sections) {
    if (!readyByKey.has(section.key)) readyByKey.set(section.key, false);
  }

  for (const section of manifest.sections) {
    await markSectionReady(manifest.id, section.key, readyByKey.get(section.key) ?? false);
  }
  const next = await getManifest(manifest.id);
  return {
    manifest: next,
    readiness: next ? computePackReadiness(next.sections) : computePackReadiness([]),
  };
}

// ── Remove ──────────────────────────────────────────────────────────────────

export interface RemoveResult {
  removedUrls: string[];
  keptSharedUrls: string[];
  /** Post-removal estimate, when the browser exposes one. */
  estimate: { usage: number; quota: number } | null;
}

/**
 * Remove a pack: delete only the URLs no OTHER manifest still pins
 * (assetsStillPinnedElsewhere), from exactly the cache each URL lives in,
 * then drop the manifest record and the plan index entry. Personal stores
 * (logbook, savedWaters, trips, photos, settings) are never opened here.
 */
export async function remove(manifest: DownloadManifestRecord): Promise<RemoveResult> {
  const others = await listManifests();
  // assetsStillPinnedElsewhere returns the URLs NO other manifest pins — the
  // set that is safe to delete. Its complement (still pinned elsewhere) stays.
  const removableSet = new Set(assetsStillPinnedElsewhere(manifest, others));
  const removedUrls: string[] = [];

  const byCache = new Map<string, Cache>();
  for (const url of manifest.assetUrls) {
    if (!removableSet.has(url)) continue;
    const name = cacheNameForUrl(url);
    try {
      if (!byCache.has(name)) byCache.set(name, await openCache(name));
      await byCache.get(name)!.delete(url);
      removedUrls.push(url);
    } catch {
      // A cache that cannot open cannot be cleaned — the manifest record is
      // still removed (the pack is gone from the UI either way); report the
      // URL as un-removed by leaving it out of removedUrls.
    }
  }

  await deleteManifest(manifest.id);
  dropPlanIndexEntry(manifest.id);
  return {
    removedUrls,
    keptSharedUrls: manifest.assetUrls.filter((url) => !removableSet.has(url)),
    estimate: await storageEstimate(),
  };
}

/** Cache names this lane may ever touch — the personal-data safety boundary,
 *  asserted in tests. */
export const PACK_OWNED_CACHES = [PACK_CACHE_NAME, TOPO_CACHE_NAME] as const;
